package com.rameysoft.easypos.ui.main.views.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDesign extends HorizontalLayout {
	protected CssLayout pos_menu;
	protected Label logo;
	protected MenuBar settings;
	protected Button valoMenuToggleButton;
	protected CssLayout menuItemsLayout;
	protected Button salesButton;
	protected Button inventryButton;
	protected Button settingsButton;
	protected CssLayout viewContainer;

	public MainDesign() {
		Design.read(this);
	}
}
